In [5]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

#1d array 
arr1=np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [3]:
print(type(arr1))
print(arr1.shape)

<class 'numpy.ndarray'>
(6,)


In [ ]:
#reshape array
arr2=np.array([1,2,3,4,5,6])
arr2.reshape(1,6)  # 1 row and 6 cols,two square [[]] means 2-d array


array([[1, 2, 3, 4, 5, 6]])

In [ ]:
# 2-d array
arr3=np.array([[1,2,3,4,5]])
arr3.shape

(1, 5)

In [7]:
arr4=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr4)
arr4.shape

[[1 2 3 4 5]
 [6 7 8 9 0]]


(2, 5)

In [8]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2).reshape(1,5) # 1 row , 5 cols
np.arange(0,10,2).reshape(5,1) # 5 row , 1 cols

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [4]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#indentity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
arr=np.array([[1,2,3,0],[4,5,6,5],[7,8,9,4]])

print("array :\n" ,arr)
print("shape :", arr.shape)
print("no of dimensions :", arr.ndim)
print("size of element :",arr.size)
print("data type :",arr.dtype)
print("item size in byte :",arr.itemsize)

array :
 [[1 2 3 0]
 [4 5 6 5]
 [7 8 9 4]]
shape : (3, 4)
no of dimensions : 2
size of element : 12
data type : int32
item size in byte : 4


In [12]:
# Vectorized operation
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([7,8,9,10,11,12])

print("addition :",arr1+arr2)
print("subtraction :",arr2-arr1)
print("multiplication :",arr1*arr2)
print("dividon :",arr2/arr1)


addition : [ 8 10 12 14 16 18]
subtraction : [6 6 6 6 6 6]
multiplication : [ 7 16 27 40 55 72]
dividon : [7.  4.  3.  2.5 2.2 2. ]


In [14]:
# unviversal function
arr=np.array([1,2,3,4,5,6])
print("square root :",np.sqrt(arr))

print("exponential :",np.exp(arr))
print("sine :",np.sin(arr))
print("natual log :",np.log(arr))

square root : [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
exponential : [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
sine : [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
natual log : [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [15]:
# array slicing 

arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("array \n",arr)

array 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [16]:
print(arr[1:])

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [19]:
print(arr[1:,1:4])

[[ 7  8  9]
 [12 13 14]]


In [24]:
print(arr[0][0])
print(arr[1][4])

1
10


In [26]:
print(arr[0:2,1:])

[[ 2  3  4  5]
 [ 7  8  9 10]]


In [27]:
arr[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15]])

In [28]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [29]:
#modify array
arr[0][0]=111
print(arr)

[[111   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [30]:
arr[2:,2:]=100

In [31]:
arr

array([[111,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12, 100, 100, 100]])

In [36]:
#Statistical concepts == normalization

data=np.array([1,2,3,4,5,6])

# Mean
mean=np.mean(data)
print(mean)

#median
median=np.median(data)
print(median)

#standard deviation
std_dev=np.std(data)
print(std_dev)

#variance
variance=np.var(data)
print(variance)

# normalization 
normalization_data=(data-mean)/std_dev
print("normalization data :",normalization_data )



3.5
3.5
1.707825127659933
2.9166666666666665
normalization data : [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


In [37]:
## logical operation

d1=np.array([1,2,3,4,5,6,7,8,9,10])

d1[(d1>5)]

array([ 6,  7,  8,  9, 10])

In [41]:
d1[(d1>=3) & (d1<=8)]

array([3, 4, 5, 6, 7, 8])