In [2]:
!pip install numpy
import numpy as np

Defaulting to user installation because normal site-packages is not writeable


In [3]:
# orignal array
arr1=np.random.randint(1,21 ,size=(5,5))
arr1

array([[19,  4,  9, 15,  7],
       [16, 11, 12, 10, 11],
       [16,  3, 18, 20, 14],
       [ 9, 14, 11, 14,  3],
       [ 1,  7,  7,  9, 14]], dtype=int32)

In [4]:
#replace value
arr1[:,2]=1
arr1

array([[19,  4,  1, 15,  7],
       [16, 11,  1, 10, 11],
       [16,  3,  1, 20, 14],
       [ 9, 14,  1, 14,  3],
       [ 1,  7,  1,  9, 14]], dtype=int32)

In [5]:
arr2=np.random.randint(1,16 ,size=(4,4))
print(arr2)
print('\n')
np.fill_diagonal(arr2,0)
print(arr2)



[[ 7 11 13  3]
 [ 9  2  9  7]
 [ 3 12  2 11]
 [ 7 10  8 11]]


[[ 0 11 13  3]
 [ 9  0  9  7]
 [ 3 12  0 11]
 [ 7 10  8  0]]


In [6]:
array=np.random.randint(1,36,size=(6,6))
print(array)


[[ 5 13 10 26 14  3]
 [23 16 17 34  2 31]
 [ 8  6 17 17  4 27]
 [35  7 17  4 34 10]
 [18 16 17 33 29 11]
 [10 15 13  3 14 10]]


In [7]:
array2=array[2:5,1:4]
array2

array([[ 6, 17, 17],
       [ 7, 17,  4],
       [16, 17, 33]], dtype=int32)

In [8]:
array=np.random.randint(1,20,size=(5,5))
print(array)

[[ 6 11 18 14 19]
 [12 13 15  6  1]
 [13 17  9  8  8]
 [ 3 11 14 17  3]
 [17  6 14 19 11]]


In [9]:
array[0:,0]

array([ 6, 12, 13,  3, 17], dtype=int32)

In [10]:
array[0:1,0:]

array([[ 6, 11, 18, 14, 19]], dtype=int32)

In [11]:
array[0:,4:]

array([[19],
       [ 1],
       [ 8],
       [ 3],
       [11]], dtype=int32)

In [12]:
array[4:,0:]

array([[17,  6, 14, 19, 11]], dtype=int32)

In [13]:
B_elements=np.concatenate((array[0:,0],array[0:1,0:],array[0:4],array[4:,0:]))
print(B_elements)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [28]:
# Create a NumPy array of shape (5, 5) with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
print("Border elements:")
print(border_elements)

Original array:
[[13 11 20 11  8]
 [14  3 20  1  8]
 [ 5  2  6  2 15]
 [16  2 20 18 11]
 [ 6  5 11  5  3]]
Border elements:
[13 11 20 11  8  6  5 11  5  3 14  5 16  8 15 11]


In [29]:
arr1=np.random.randint(1,12,size=(3,4))
arr2=np.random.randint(1,12,size=(3,4))
print("array 1st :\n ",arr1)
print("array 2nd : \n",arr2)

print("addition : \n",arr1+arr2)
print("subtraction : \n",arr1-arr2)
print("division : \n",arr1-arr2)
print("multiplication : \n",arr1*arr2)

array 1st :
  [[ 5  6  9 11]
 [ 1  2  4  3]
 [ 3  6 11  3]]
array 2nd : 
 [[ 4  7  2 11]
 [ 8  8  2 10]
 [ 4  8  5  1]]
addition : 
 [[ 9 13 11 22]
 [ 9 10  6 13]
 [ 7 14 16  4]]
subtraction : 
 [[ 1 -1  7  0]
 [-7 -6  2 -7]
 [-1 -2  6  2]]
division : 
 [[ 1 -1  7  0]
 [-7 -6  2 -7]
 [-1 -2  6  2]]
multiplication : 
 [[ 20  42  18 121]
 [  8  16   8  30]
 [ 12  48  55   3]]


In [43]:
array1=np.random.randint(1,16,size=(4,4))
print(array1)

row_sum = np.sum(array1, axis=1)
col_sum = np.sum(array1,axis=0)
print("addtion row :",row_sum)
print("addition column :",col_sum)

print("addition_row :",np.sum(array1[0:,0:5],axis=1))
print("addition column :",np.sum(array1[0:5,0:],axis=0))

[[ 3  3  9  1]
 [ 1  5 14  5]
 [10 15 11  3]
 [13 13  8 14]]
addtion row : [16 25 39 48]
addition column : [27 36 42 23]
addition_row : [16 25 39 48]
addition column : [27 36 42 23]


In [48]:
array=np.random.randint(1,25,size=(5,5))
print(array)

print("mean : ",np.mean(array))
print("median :",np.median(array))
print("standard deviation :",np.std(array))
print("variance :",np.var(array))

[[22 14  7 18 17]
 [ 9 19 22 11 18]
 [19  8  2 22 24]
 [ 4 10 18 11 13]
 [19 15  3 14 18]]
mean :  14.28
median : 15.0
standard deviation : 6.161298564426171
variance : 37.9616


In [49]:
array=np.random.randint(1,9,size=(3,3))
print(array)

mean=np.mean(array)
std=np.std(array)
normalization=(array-mean)/std
print("normalization :",normalization)

[[7 6 8]
 [2 5 6]
 [2 7 8]]
normalization : [[ 0.6172134   0.15430335  1.08012345]
 [-1.69733685 -0.3086067   0.15430335]
 [-1.69733685  0.6172134   1.08012345]]


In [50]:
arr1=np.random.randint(1,9,size=(3,3))
arr2=np.random.randint(1,9,size=(3,))

print(arr1)
print(arr2)

sum_arr=arr1+arr2
print("sum_arr :\n",sum_arr)

[[2 2 3]
 [1 2 5]
 [4 7 8]]
[1 3 7]
sum_arr :
 [[ 3  5 10]
 [ 2  5 12]
 [ 5 10 15]]


In [52]:
arr1=np.random.randint(1,16,size=(4,4))
arr2=np.random.randint(1,16,size=(4,))
print(arr1)
print(arr2)

sub_arr=arr1-arr2
print("sum_arr :",sub_arr)


[[11  8 15 12]
 [ 3 15 10  3]
 [ 4  6 13  9]
 [ 9  1  7 10]]
[14  4 14 12]
sum_arr : [[ -3   4   1   0]
 [-11  11  -4  -9]
 [-10   2  -1  -3]
 [ -5  -3  -7  -2]]


In [57]:
matrix=np.random.randint(1,11,size=(3,3))
print(matrix)

determinant=np.linalg.det(matrix)
print("determination :",determinant)

inverse=np.linalg.inv(matrix)
print("inverse :",inverse)

eigenvalues=np.linalg.eig(matrix)
print("eigenvalues :",eigenvalues)

[[ 4  4 10]
 [ 8  1  6]
 [ 6  6  4]]
determination : 307.9999999999999
inverse : [[-1.03896104e-01  1.42857143e-01  4.54545455e-02]
 [ 1.29870130e-02 -1.42857143e-01  1.81818182e-01]
 [ 1.36363636e-01 -3.78485122e-18 -9.09090909e-02]]
eigenvalues : EigResult(eigenvalues=array([16.45682401+0.j       , -3.728412  +2.1942161j,
       -3.728412  -2.1942161j]), eigenvectors=array([[ 0.62509315+0.j        ,  0.24675003-0.52152717j,
         0.24675003+0.52152717j],
       [ 0.5416837 +0.j        , -0.65126562+0.j        ,
        -0.65126562-0.j        ],
       [ 0.56199406+0.j        ,  0.18424199+0.45719997j,
         0.18424199-0.45719997j]]))


In [64]:
arr1=np.random.randint(1,11,size=(2,3))
arr2=np.random.randint(1,11,size=(3,2))
print("array 1: \n",arr1)
print("array 2: \n ",arr2)

# matrix multiplication
multiplication=np.dot(arr1,arr2)
print(multiplication)

array 1: 
 [[10  9  5]
 [ 4  7  2]]
array 2: 
  [[7 5]
 [3 7]
 [3 7]]
[[112 148]
 [ 55  83]]


In [67]:
array=np.random.randint(1,9,size=(3,3))
print(array)

resize=array.reshape(1,9)
print("resize : \n",resize)

resize=array.reshape(9,1)
print("resize : \n",resize)

[[3 8 6]
 [6 3 2]
 [6 3 2]]
resize : 
 [[3 8 6 6 3 2 6 3 2]]
resize : 
 [[3]
 [8]
 [6]
 [6]
 [3]
 [2]
 [6]
 [3]
 [2]]


In [68]:
array=np.random.randint(1,25,size=(5,5))
print(array)

flatter_arr=array.flatten()
print("flatter_arr : \n",flatter_arr)

reshape_arr=flatter_arr.reshape(5,5)
print("reshape arr :\n",reshape_arr)

[[ 4 12 21 14 21]
 [ 1  3 21 19 13]
 [10  7 10 15  7]
 [13  8  6 15 11]
 [10 16 16  3 20]]
flatter_arr : 
 [ 4 12 21 14 21  1  3 21 19 13 10  7 10 15  7 13  8  6 15 11 10 16 16  3
 20]
reshape arr :
 [[ 4 12 21 14 21]
 [ 1  3 21 19 13]
 [10  7 10 15  7]
 [13  8  6 15 11]
 [10 16 16  3 20]]


In [69]:
array=np.random.randint(1,11,size=(5,5))
print(array)

corners=array[[0,0,-1,-1],[0,-1,0,-1]]
print(corners)

[[ 4 10  9  4  8]
 [ 5  4  4 10  2]
 [ 9  9  8  7  3]
 [ 3  2  6  6  5]
 [ 8  6  2  6  2]]
[4 8 8 2]


In [73]:
corners=array[[0,0],[0,-1]]
print(corners)

[4 8]


In [75]:
array=np.random.randint(1,16,size=(4,4))
print(array)

array[array > 10] = 10
print("modified array :",array)

[[11 12 15  5]
 [13  4  5 10]
 [14  4 10  8]
 [11  9 11  5]]
modified array : [[10 10 10  5]
 [10  4  5 10]
 [10  4 10  8]
 [10  9 10  5]]


In [21]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print(data)

sorted_data=np.sort(data,order='age')
print("sorted_data :\n",sorted_data)

[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
sorted_data :
 [('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [25]:
data_type=[('x','i4'),('y','i4')]
data=np.array([(2,4),(5,7),(8,4)], dtype=data_type)
print(data)

distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

[(2, 4) (5, 7) (8, 4)]
Euclidean distances:
[[0.         4.24264069 6.        ]
 [4.24264069 0.         4.24264069]
 [6.         4.24264069 0.        ]]


In [26]:
import numpy.ma as ma

data=np.random.randint(1,21 ,size=(4,4))
mask_Array=ma.masked_greater(data,10)
print("array : \n",data)
print("mask_arrat :\n",mask_Array)

sum_unmask=mask_Array.sum()
print("sum_unmask :\n",sum_unmask)




array : 
 [[ 8 11  9 14]
 [11  2  9 14]
 [17  9 10 15]
 [ 1  2  2  9]]
mask_arrat :
 [[8 -- 9 --]
 [-- 2 9 --]
 [-- 9 10 --]
 [1 2 2 9]]
sum_unmask :
 61
